version: '3.8'
services:
  nginx:
    image: nginx:1.25
    container_name: huitzilin-nginx
    volumes:
    - ./nginx/blue-green.conf:/etc/nginx/conf.d/default.conf:ro

    ports:
      - "80:80"
    networks:
      - huitzilin_net

networks:
  huitzilin_net:
    external: true
